### ISSUE TITLE
missing picture

### ISSUE THREAD

**Issue by sandgate-dev** [learn-co-curriculum/dsc-2-20-05-effect-sizes#1]
Before the following text there seems to be a image missing:

> The "overlap" (shaded region above) is the total AUC (Area Under the Curves). We can use this to identify the sample that end up on the wrong side of the threshold. We can calculate the amount of overlap as shown below.

**Comment by L-Lewis** [comment]
This is still the case - the AUC image just shows as a broken image icon and is missing. Can it be added in please?

**Comment by fpolchow** [comment]
AUC image has been added
